spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: springboot-https
  datasource:
    url: jdbc:postgresql://localhost:5442/secure_pg_db
    username: ${USERNAME}
    password: ${PASSWORD}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:test
    key-store-password: ${KEY_STORE_PASS}
    key-store-type: PKCS12
    key-alias: springboot

logging:
  level:
    org:
      hibernate:
        sql: trace
      springframework:
        context: info
        security: trace

